apiVersion: v1
kind: Service
metadata:
  name: capstone

spec:
  selector:
    app: capstone
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone

spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: project4udacity/capstone-app
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources: {}