apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-frontend
  template:
    metadata:
      labels:
        app: capstone-frontend
    spec:
      containers:
      - name: capstone-frontend
        image: sabribouchlema/capstone-frontend:${CIRCLE_SHA1}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: capstone-frontend